main: com.winthier.tpa.TPAPlugin
name: TPA

version: 0.1
api-version: '1.20'

description: Teleport request
author: StarTux
website: https://github.com/StarTux/TPA

depend: [Core, PlayerCache, Chat, Connect]
softdepend: []

commands:

  tpa:
    description: Request teleport to another player.
    usage: /<command> <player>
    permission: tpa.tpa

  bring:
    description: Accept a teleport request
    permission: tpa.tpa
    usage: /<command> <player>

permissions:

  tpa.tpa:
    description: Use the /tpa command
    default: op

  tpa.nocooldown:
    description: Skip cooldowns
    default: op