main: com.winthier.tpa.TPAPlugin
name: TPA
description: Teleport request
author: StarTux
version: 0.1
api-version: 1.13
website: https://github.com/StarTux/TPA
depend: [Chat]
softdepend: []
commands:
  tpa:
    description: Request teleport to another player.
    usage: /<command> <player>
    permission: tpa.tpa
  bring:
    description: Accept a teleport request
    usage: /<command> <player>
    permission: tpa.tpa
permissions:
  tpa.tpa:
    description: Use the /tpa command
    default: op
  tpa.admin:
    description: Use admin commands
    default: op